fonttools/fontspector

- profile-googlefonts/Cargo.toml
- profile-googlefonts/src/checks/tofu.rs
- profile-googlefonts/src/metadata_subsets_correct.rs
- profile-universal/Cargo.toml
- profile-universal/src/checks/tabular_kerning.rs
It shouldn't take more than a minute to check the whole catalogue!
> Optimizations

- Cargo.lock
- fontspector-checkapi/src/check.rs
- fontspector-checkapi/src/filetype.rs
- fontspector-checkapi/src/status.rs
- fontspector-cli/src/main.rs
- fontspector-py/tests/test_checks_googlefonts.py
- profile-googlefonts/Cargo.toml
- profile-googlefonts/src/checks/googlefonts/description/broken_links.rs
- profile-googlefonts/src/checks/googlefonts/description/git_url.rs
- profile-googlefonts/src/checks/googlefonts/description/has_article.rs
- profile-googlefonts/src/checks/googlefonts/description/has_unsupported_elements.rs
- profile-googlefonts/src/checks/googlefonts/description/mod.rs
- profile-googlefonts/src/checks/googlefonts/description/urls.rs
- profile-googlefonts/src/checks/googlefonts/description/valid_html.rs
- profile-googlefonts/src/lib.rs
- profile-opentype/src/checks/opentype/family/panose_familytype.rs
All the description checks except `googlefonts/description/family_update` which is only useful if you're PRing a family update and fails horribly if you're repeatedly checking the whole collection.
> Description checks

- Cargo.lock
- fontspector-py/tests/test_checks_googlefonts.py
- profile-googlefonts/src/checks/googlefonts/name/license.rs
- profile-googlefonts/src/checks/googlefonts/name/mod.rs
- profile-googlefonts/src/lib.rs
@simoncozens, for this one, I need some help reading the license file. I guess it should be possible to get it maybe from a TestableCollection?
> port `googlefonts/name/license`

- profile-universal/src/checks/fontdata_namecheck.rs
Counterpart to https://github.com/fonttools/fontbakery/pull/4980/
> Use namecheck API

- fontspector-checkapi/src/font.rs
- fontspector-checkapi/src/testable.rs
- fontspector-py/tests/test_checks_googlefonts.py
- profile-googlefonts/Cargo.toml
- profile-googlefonts/src/checks/googlefonts/axes_match.rs
- profile-googlefonts/src/checks/googlefonts/canonical_filename.rs
- profile-googlefonts/src/checks/googlefonts/glyph_coverage.rs
- profile-googlefonts/src/checks/googlefonts/mod.rs
- profile-googlefonts/src/checks/googlefonts/version_bump.rs
- profile-googlefonts/src/lib.rs
- profile-googlefonts/src/network_conditions.rs
- **Canonical filename check**
- **remote_styles condition**
- **Finish up axes_match check**
- **googlefonts/version_bump**
- **Oops, check codepoints per file**
- **glyph_coverage**
> More font file checks

- README.md
> Update URL for web version

- fontspector-cli/Cargo.toml
- fontspector-cli/src/args.rs
- fontspector-cli/src/main.rs
- fontspector-cli/src/reporters/csv.rs
- fontspector-cli/src/reporters/mod.rs
- profile-googlefonts/src/checks/googlefonts/axes_match.rs
- profile-googlefonts/src/network_conditions.rs
- profile-universal/src/checks/mod.rs
- profile-universal/src/checks/ytlc_sanity.rs
- profile-universal/src/lib.rs
- profiles/fontbureau.toml
- profiles/fontwerk.toml
- scripts/port_profile.py
* Support loading external profiles from TOML files
* A script to port Fontbakery profiles to TOML profiles
* A missing check for the fontwerk profille
* And the fontwerk profile itself, as TOML
* Oh, and a CSV reporter
> CSV, fontwerk, TOML profiles

- fontspector-checkapi/src/status.rs
- fontspector-cli/Cargo.toml
- fontspector-cli/src/args.rs
- fontspector-cli/src/main.rs
- fontspector-cli/src/reporters/duckdb.rs
- fontspector-cli/src/reporters/mod.rs
- **Reorder status again**
- **Add duckdb reporter**
> Add DuckDB reporter

- Cargo.toml
- fontspector-checkapi/src/check.rs
- fontspector-cli/Cargo.toml
- profile-googlefonts/Cargo.toml
- **Tidy dependencies**
- **Also some info debugging**
> Dependency tidying

- fontspector-checkapi/src/profile.rs
- profile-googlefonts/src/checks/googlefonts/font_copyright.rs
- profile-googlefonts/src/lib.rs
- profile-universal/src/checks/stylisticset_description.rs
- **Exclude checks marked as excluded by profile**
- **Exclude pending_review checks included from other profiles**
- **Only warn once per feature**
- **Clarify which name table entry**
> reduce false positives

- .github/ISSUE_TEMPLATE/1_improve-check.md
- .github/ISSUE_TEMPLATE/2_new-check.md
- .github/ISSUE_TEMPLATE/3_general-issue.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
> Copy fontbakery github templates

- Cargo.toml
- fontspector-cli/Cargo.toml
- fontspector-cli/src/main.rs
- fontspector-web/Cargo.toml
- fontspector-web/src/lib.rs
- fontspector-web/www/index.ts
- package.json
- profile-googlefonts/Cargo.toml
- profile-iso15008/Cargo.toml
- profile-iso15008/src/checks/iso15008/intercharacter_spacing.rs
- profile-iso15008/src/checks/iso15008/interline_spacing.rs
- profile-iso15008/src/checks/iso15008/interword_spacing.rs
- profile-iso15008/src/checks/iso15008/mod.rs
- profile-iso15008/src/checks/iso15008/proportions.rs
- profile-iso15008/src/checks/iso15008/stem_width.rs
- profile-iso15008/src/checks/mod.rs
- profile-iso15008/src/lib.rs
- **Oh hey, this can be built on wasm too**
- **Add ISO15008 profile**
- **Bake it in**
> ISO15008 profile

- Cargo.lock
- Cargo.toml
- fontspector-checkapi/Cargo.toml
- fontspector-checkapi/src/codetesting.rs
- fontspector-checkapi/src/context.rs
- fontspector-checkapi/src/profile.rs
- fontspector-cli/Cargo.toml
- fontspector-cli/src/configuration.rs
- fontspector-cli/src/main.rs
- fontspector-py/src/lib.rs
- fontspector-web/src/lib.rs
- profile-opentype/src/checks/opentype/vendor_id.rs
- **feat(cli): Allow TOML config, allow explicit_checks/exclude_checks keys**
- **fix(opentype/vendor_id): Support config file key property**
> feat(cli): Allow TOML config, allow explicit_checks/exclude_checks keys

- renovate.json
> chore(deps): Add renovate config

- Cargo.lock
- Cargo.toml
> chore(web): Temporarily patch tabled until new version is out

- fontspector-web/www/webpack.config.js
> chore(web): Update Copy Plugin args to rolled version

- fontspector-py/tests/test_checks_cjk.py
- fontspector-py/tests/test_checks_filesize.py
- fontspector-py/tests/test_checks_googlefonts.py
- fontspector-py/tests/test_checks_opentype_name.py
- fontspector-py/tests/test_checks_shaping.py
- fontspector-py/tests/test_checks_universal.py
- profile-googlefonts/src/checks/googlefonts/cjk_vertical_metrics.rs
We now have a new [CJK vertical metrics schema](https://googlefonts.github.io/gf-guide/metrics.html#cjk-vertical-metrics), which means the check needs to follow it.
This is a WIP as:
> feat(googlefonts): New GF CJK vertical metrics schema

- profile-googlefonts/src/checks/googlefonts/name/mandatory_entries.rs
> feat(googlefonts): Add designer name to mandatory name table entries (#227)

- fontspector-cli/src/reporters/jinja.rs
- fontspector-cli/src/reporters/mod.rs
- fontspector-cli/src/reporters/terminal.rs
> chore(reporters): Order result summary bad to good

- fontspector-py/Cargo.toml
- fontspector-web/Cargo.toml
- profile-adobe/Cargo.toml
- profile-designspace/Cargo.toml
- profile-microsoft/Cargo.toml
- profile-testplugin/Cargo.toml
- scripts/publishable.py
- **chore: Deny publishing these crates**
- **chore(ci): Add a script to find the publishable crates**
> chore(ci): Create list of publishable packages, send to smart-release

- Cargo.lock
- Cargo.toml
- fontspector-checkapi/src/filetype.rs
- fontspector-checkapi/src/font.rs
- fontspector-checkapi/src/registry.rs
- fontspector-checkapi/src/testable.rs
- fontspector-cli/src/reporters/mod.rs
- profile-universal/src/checks/integer_ppem_if_hinted.rs
- **chore: Upgrade fontations deps**
- **chore: API changed**
> chore: get working again

- USING.md
- fontspector-checkapi/src/profile.rs
- **feat(cli): Add per-font inclusions and exclusions**
- **docs: Start a 'using' doc**
> feat(cli): Add per-font inclusions and exclusions

- USING.md
- fontspector-cli/src/args.rs
> fix(--help):  configuration file type: TOML/JSON
